# Generated by Django 4.2.8 on 2024-11-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autenticacao', '0003_medicamento_registrado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='autenticacao.estabelecimento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.medicamento')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_saida', to='autenticacao.estabelecimento')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.estabelecimento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.medicamento')),
            ],
            options={
                'unique_together': {('medicamento', 'estabelecimento')},
            },
        ),
    ]
