# Generated by Django 4.2.8 on 2024-11-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_transferencia_estoquemedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.estabelecimento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.medicamento')),
            ],
        ),
        migrations.DeleteModel(
            name='EstoqueMedicamento',
        ),
    ]
