# Generated by Django 4.2.8 on 2024-11-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_estoque_delete_estoquemedicamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='quantidade',
            new_name='estoque',
        ),
    ]
